spring.application.name=TallerApi

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/proyectocertificado
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Ruta para guardar las imágenes
upload.path=./uploads

# Tamaño máximo de archivo para uploads (20MB)
# Tamaños para multipart (funciona con StandardServletMultipartResolver)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB

# Hibernate (opcional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect